### ISSUE TITLE
Measuring tool

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#58] opened 2018-01-24 21:24 UTC
Need ability to measure size of pictures, images and text boxes.

**Comment by hermbit** [comment] 2018-01-29 09:03
Is THIS one a duplicate of #40? Or referring to something else?

**Comment by Joshrlear** [comment] 2018-01-29 15:13
I believe 40 was just for shapes while 58 is for pics and everything else
but for the most part I guess you could combine the two issues together.

**Closed** 2018-01-30 21:58 UTC
Labels: admin-designer, enhancement
